# Библиотека Pandas

Pandas — самая популярная библиотека Python для обработки и анализа данных. Предлагает высокопроизводительные структуры данных и инструменты, которые решают следующие задачи:

* **загрузка данных** из внешних источников (электронный таблиц, баз данных, веб-страниц и прочих разных)
* **сохранение данных** в требуемом формате
* объединение данных, полученных из разных источников
* очистка данных от пропусков и ошибок
* **группировка и агрегирование данных**
* преобразование данных
* выполнение запросов для исследования данных
* создание новых атрибутов/признаков данных

In [1]:
import pandas as pd

## Загрузка данных в объект DataFrame

ссылка на файл - https://drive.google.com/file/d/1hiJUAB5NA6B-Jqk3Bv3zjg_3rJ17qydJ/view?usp=sharing

In [2]:
!gdown 1hiJUAB5NA6B-Jqk3Bv3zjg_3rJ17qydJ

Downloading...
From: https://drive.google.com/uc?id=1hiJUAB5NA6B-Jqk3Bv3zjg_3rJ17qydJ
To: /content/IMDB-Movie-Data.csv
100% 310k/310k [00:00<00:00, 34.7MB/s]

In [3]:
df = pd.read_csv('/content/IMDB-Movie-Data.csv')
df.head()

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
0,1,Guardians of the Galaxy,"Action,Adventure,Sci-Fi",A group of intergalactic criminals are forced ...,James Gunn,"Chris Pratt, Vin Diesel, Bradley Cooper, Zoe S...",2014,121,8.1,757074,333.13,76.0
1,2,Prometheus,"Adventure,Mystery,Sci-Fi","Following clues to the origin of mankind, a te...",Ridley Scott,"Noomi Rapace, Logan Marshall-Green, Michael Fa...",2012,124,7.0,485820,126.46,65.0
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
3,4,Sing,"Animation,Comedy,Family","In a city of humanoid animals, a hustling thea...",Christophe Lourdelet,"Matthew McConaughey,Reese Witherspoon, Seth Ma...",2016,108,7.2,60545,270.32,59.0
4,5,Suicide Squad,"Action,Adventure,Fantasy",A secret government agency recruits some of th...,David Ayer,"Will Smith, Jared Leto, Margot Robbie, Viola D...",2016,123,6.2,393727,325.02,40.0

In [4]:
df.tail(2)

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
998,999,Search Party,"Adventure,Comedy",A pair of friends embark on a mission to reuni...,Scot Armstrong,"Adam Pally, T.J. Miller, Thomas Middleditch,Sh...",2014,93,5.6,4881,NaN,22.0
999,1000,Nine Lives,"Comedy,Family,Fantasy",A stuffy businessman finds himself trapped ins...,Barry Sonnenfeld,"Kevin Spacey, Jennifer Garner, Robbie Amell,Ch...",2016,87,5.3,12435,19.64,11.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Rank                1000 non-null   int64
 1   Title               1000 non-null   object
 2   Genre               1000 non-null   object
 3   Description         1000 non-null   object
 4   Director            1000 non-null   object
 5   Actors              1000 non-null   object
 6   Year                1000 non-null   int64
 7   Runtime (Minutes)   1000 non-null   int64
 8   Rating              1000 non-null   float64
 9   Votes               1000 non-null   int64
 10  Revenue (Millions)  872 non-null    float64
 11  Metascore           936 non-null    float64
dtypes: float64(3), int64(4), object(5)
memory usage: 93.9+ KB

In [6]:
df.shape

(1000, 12)

## Выборка и обобщение данных
   
len()  
.count()  
.nunique()  
.value_counts()   
.sum()  
.min() и .max()  
.mean()  
.median()

In [7]:
df.loc[df['Director'] == 'Ridley Scott', ['Title', 'Year']].shape[0]

8

In [8]:
len(df.loc[df['Director'] == 'Ridley Scott', ['Title']])

8

In [9]:
df.loc[df['Year'] == 2010, 'Title']

80                                             Inception
138                                       Shutter Island
141                                 Diary of a Wimpy Kid
158                          Scott Pilgrim vs. the World
219                                             Kick-Ass
227                                            Predators
244    Percy Jackson & the Olympians: The Lightning T...
261                                           Black Swan
304                               She's Out of My League
324                                   The Social Network
387                                           Robin Hood
403                                        Despicable Me
407                                              Tangled
418         Harry Potter and the Deathly Hallows: Part 1
428                                          Srpski film
443                                       Blue Valentine
450                                           Iron Man 2
460                                             The Town
466                                                 Salt
469                                       The Other Guys
490                                           Stake Land
491                                      The Book of Eli
515                                               Easy A
524                                                Trust
540                                     The Ghost Writer
547                                  Alice in Wonderland
560                                      The Expendables
575                                  Clash of the Titans
577                                                 Tron
579                                      All Good Things
581                                   The Last Airbender
595                                            Let Me In
599                                             Megamind
606                                        Winter's Bone
630                                   Love & Other Drugs
652                                            Insidious
685                                    The King's Speech
688                                          Toy Story 3
702                                                  RED
704                                               Faster
713                                            Incendies
722                                            Grown Ups
724                                       The Karate Kid
728                                           The A-Team
743                                            True Grit
759                                          The Fighter
772                             How to Train Your Dragon
806                  Prince of Persia: The Sands of Time
817                                            127 Hours
844                                          Unstoppable
860                                          Remember Me
874                                   Life as We Know It
888                                           Piranha 3D
920                                            Centurion
937                                                Super
941                           The Twilight Saga: Eclipse
952                                   Sex and the City 2
956                                               Legion
963                                 I Spit on Your Grave
993                             Resident Evil: Afterlife
Name: Title, dtype: object

In [10]:
len(df[df['Year'] == 2010])

60

In [11]:
df[(df['Year'] == 2010) & (df['Director'] == 'Ridley Scott')] # AND

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
387,388,Robin Hood,"Action,Adventure,Drama","In 12th century England, Robin and his band of...",Ridley Scott,"Russell Crowe, Cate Blanchett, Matthew Macfady...",2010,140,6.7,221117,105.22,53.0

In [12]:
df[df['Genre'] == 'Horror']

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
42,43,Don't Fuck in the Woods,Horror,A group of friends are going on a camping trip...,Shawn Burkett,"Brittany Blanton, Ayse Howard, Roman Jossart,N...",2016,73,2.7,496,NaN,NaN
258,259,Lights Out,Horror,Rebecca must unlock the terror behind her litt...,David F. Sandberg,"Teresa Palmer, Gabriel Bateman, Maria Bello,Bi...",2016,81,6.4,69823,67.24,58.0
269,270,Satanic,Horror,Four friends on their way to Coachella stop of...,Jeffrey G. Hunt,"Sarah Hyland, Steven Krueger, Justin Chon, Cla...",2016,85,3.7,2384,NaN,NaN
302,303,The Cabin in the Woods,Horror,"Five friends go for a break at a remote cabin,...",Drew Goddard,"Kristen Connolly, Chris Hemsworth, Anna Hutchi...",2012,95,7.0,295554,42.04,72.0
401,402,The Black Room,Horror,PAUL and JENNIFER HEMDALE have just moved into...,Rolfe Kanefsky,"Natasha Henstridge, Lukas Hassel, Lin Shaye,Do...",2016,91,3.9,240,NaN,71.0
623,624,Friday the 13th,Horror,A group of young adults discover a boarded up ...,Marcus Nispel,"Jared Padalecki, Amanda Righetti, Derek Mears,...",2009,97,5.6,78631,65.00,34.0
675,676,The Mist,Horror,A freak storm unleashes a species of bloodthir...,Frank Darabont,"Thomas Jane, Marcia Gay Harden, Laurie Holden,...",2007,126,7.2,233346,25.59,58.0
858,859,The Hills Have Eyes,Horror,A suburban American family is being stalked by...,Alexandre Aja,"Ted Levine, Kathleen Quinlan, Dan Byrd, Emilie...",2006,107,6.4,136642,41.78,52.0
936,937,The Human Centipede (First Sequence),Horror,A mad scientist kidnaps and mutilates a trio o...,Tom Six,"Dieter Laser, Ashley C. Williams, Ashlynn Yenn...",2009,92,4.4,60655,0.18,33.0
988,989,Martyrs,Horror,A young woman's quest for revenge against the ...,Pascal Laugier,"Morjana Alaoui, Mylène Jampanoï, Catherine Bég...",2008,99,7.1,63785,NaN,89.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0

In [13]:
df[df['Genre'].str.contains('Horror')]

,Rank,Title,Genre,Description,Director,Actors,Year,Runtime (Minutes),Rating,Votes,Revenue (Millions),Metascore
2,3,Split,"Horror,Thriller",Three girls are kidnapped by a man with a diag...,M. Night Shyamalan,"James McAvoy, Anya Taylor-Joy, Haley Lu Richar...",2016,117,7.3,157606,138.12,62.0
22,23,Hounds of Love,"Crime,Drama,Horror",A cold-blooded predatory couple while cruising...,Ben Young,"Emma Booth, Ashleigh Cummings, Stephen Curry,S...",2016,108,6.7,1115,NaN,72.0
27,28,Dead Awake,"Horror,Thriller",A young woman must save herself and her friend...,Phillip Guzman,"Jocelin Donahue, Jesse Bradford, Jesse Borrego...",2016,99,4.7,523,0.01,NaN
34,35,Resident Evil: The Final Chapter,"Action,Horror,Sci-Fi",Alice returns to where the nightmare began: Th...,Paul W.S. Anderson,"Milla Jovovich, Iain Glen, Ali Larter, Shawn R...",2016,107,5.6,46165,26.84,49.0
42,43,Don't Fuck in the Woods,Horror,A group of friends are going on a camping trip...,Shawn Burkett,"Brittany Blanton, Ayse Howard, Roman Jossart,N...",2016,73,2.7,496,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
973,974,Scream 4,"Horror,Mystery","Ten years have passed, and Sidney Prescott, wh...",Wes Craven,"Neve Campbell, Courteney Cox, David Arquette, ...",2011,111,6.2,108544,38.18,52.0
986,987,Final Destination 5,"Horror,Thriller",Survivors of a suspension-bridge collapse lear...,Steven Quale,"Nicholas D'Agosto, Emma Bell, Arlen Escarpeta,...",2011,92,5.9,88000,42.58,50.0
988,989,Martyrs,Horror,A young woman's quest for revenge against the ...,Pascal Laugier,"Morjana Alaoui, Mylène Jampanoï, Catherine Bég...",2008,99,7.1,63785,NaN,89.0
993,994,Resident Evil: Afterlife,"Action,Adventure,Horror",While still out to destroy the evil Umbrella C...,Paul W.S. Anderson,"Milla Jovovich, Ali Larter, Wentworth Miller,K...",2010,97,5.9,140900,60.13,37.0
996,997,Hostel: Part II,Horror,Three American college students studying abroa...,Eli Roth,"Lauren German, Heather Matarazzo, Bijou Philli...",2007,94,5.5,73152,17.54,46.0

In [14]:
df['Director'].nunique()

644

In [15]:
df['Director'].value_counts().head(10)

Director
Ridley Scott          8
David Yates           6
Paul W.S. Anderson    6
Michael Bay           6
M. Night Shyamalan    6
Christopher Nolan     5
Peter Berg            5
Justin Lin            5
J.J. Abrams           5
Danny Boyle           5
Name: count, dtype: int64

In [16]:
sum(df['Revenue (Millions)'])

nan

In [37]:
print(df['Revenue (Millions)'].sum())

72337.95999999999

## Группировка данных

`DataFrame.groupby(by = grouping_columns)[columns_to_show].function()`

Найдем медиану рейтинга фильмов каждого режиссера.

In [18]:
df.groupby('Director')['Rating'].median()

Director
Aamir Khan             8.50
Abdellatif Kechiche    7.80
Adam Leon              6.50
Adam McKay             6.80
Adam Shankman          6.30
                       ...
Xavier Dolan           7.55
Yimou Zhang            6.10
Yorgos Lanthimos       7.20
Zack Snyder            7.10
Zackary Adler          5.10
Name: Rating, Length: 644, dtype: float64

Найдем средний рейтинг фильмов каждого жанра и отсортируем по убыванию.

In [19]:
df.groupby('Genre')['Rating'].mean().sort_values(ascending=False).head(3)

Genre
Animation,Drama,Fantasy    8.6
Drama,Family,Music         8.5
Drama,Western              8.4
Name: Rating, dtype: float64

Выведем данные одной группы - get_group()

In [20]:
df.groupby('Genre').get_group('Action,Adventure')[['Genre', 'Title', 'Rating']]

                Genre                   Title  Rating
284  Action,Adventure                Hercules     6.0
344  Action,Adventure            Spider-Man 3     6.2
368  Action,Adventure  The Amazing Spider-Man     7.0

Если надо для каждой группы посчитать не одну функцию.

In [21]:
df.groupby('Genre')['Rating'].agg(['min', 'mean', 'max'])

                            min      mean  max
Genre
Action                      4.9  6.150000  7.4
Action,Adventure            6.0  6.400000  7.0
Action,Adventure,Biography  6.9  7.000000  7.1
Action,Adventure,Comedy     5.7  6.592857  8.0
Action,Adventure,Crime      5.6  6.433333  7.6
...                         ...       ...  ...
Romance,Sci-Fi,Thriller     7.1  7.100000  7.1
Sci-Fi                      4.0  4.950000  5.9
Sci-Fi,Thriller             5.0  5.000000  5.0
Thriller                    4.6  5.955556  7.1
Thriller,War                6.0  6.000000  6.0

[207 rows x 3 columns]

In [22]:
df.groupby('Genre')['Rating'].agg(
      rating_min='min',
      rating_mean='mean',
      rating_max='max'
)

                            rating_min  rating_mean  rating_max
Genre
Action                             4.9     6.150000         7.4
Action,Adventure                   6.0     6.400000         7.0
Action,Adventure,Biography         6.9     7.000000         7.1
Action,Adventure,Comedy            5.7     6.592857         8.0
Action,Adventure,Crime             5.6     6.433333         7.6
...                                ...          ...         ...
Romance,Sci-Fi,Thriller            7.1     7.100000         7.1
Sci-Fi                             4.0     4.950000         5.9
Sci-Fi,Thriller                    5.0     5.000000         5.0
Thriller                           4.6     5.955556         7.1
Thriller,War                       6.0     6.000000         6.0

[207 rows x 3 columns]

Если считаем не по одному столбцу.

In [23]:
df.groupby('Director').agg(
    num_films=('Title', 'count'),
    votes_mean=('Votes', 'mean'),
    revenue_sum=('Revenue (Millions)', 'sum')
).sort_values('num_films', ascending=False)

                    num_films     votes_mean  revenue_sum
Director
Ridley Scott                8  260009.250000       719.06
Paul W.S. Anderson          6  109576.166667       208.92
David Yates                 6  338975.666667      1630.51
M. Night Shyamalan          6  130712.333333       370.49
Michael Bay                 6  284421.833333      1421.32
...                       ...            ...          ...
Jackson Stewart             1    2127.000000         0.00
J.D. Dillard                1     702.000000         3.85
Jeff Grace                  1     220.000000         0.00
Jee-woon Kim                1    2403.000000         0.54
Jalil Lespert               1     726.000000         0.00

[644 rows x 3 columns]

## Сводные таблицы

In [24]:
pd.pivot_table(data=df,
               index='Director',
               values='Votes',
               aggfunc='mean'
)

                         Votes
Director
Aamir Khan           102697.00
Abdellatif Kechiche  103150.00
Adam Leon              1031.00
Adam McKay           201706.75
Adam Shankman         83733.50
...                        ...
Xavier Dolan          22109.00
Yimou Zhang           56036.00
Yorgos Lanthimos      86129.50
Zack Snyder          460308.80
Zackary Adler          1630.00

[644 rows x 1 columns]

In [25]:
pd.pivot_table(data=df,
               index='Director',
               values=['Title', 'Votes', 'Revenue (Millions)'],
               aggfunc={'Title': 'count',
                        'Votes': 'mean',
                        'Revenue (Millions)': 'sum'}
               ).sort_values('Title', ascending=False)

                    Revenue (Millions)  Title          Votes
Director
Ridley Scott                    719.06      8  260009.250000
Paul W.S. Anderson              208.92      6  109576.166667
David Yates                    1630.51      6  338975.666667
M. Night Shyamalan              370.49      6  130712.333333
Michael Bay                    1421.32      6  284421.833333
...                                ...    ...            ...
Jackson Stewart                   0.00      1    2127.000000
J.D. Dillard                      3.85      1     702.000000
Jeff Grace                        0.00      1     220.000000
Jee-woon Kim                      0.54      1    2403.000000
Jalil Lespert                     0.00      1     726.000000

[644 rows x 3 columns]

In [26]:
pd.pivot_table(data=df,
               index='Director',
               values=['Title', 'Votes', 'Revenue (Millions)'],
               aggfunc={'Title': 'count',
                        'Votes': 'mean',
                        'Revenue (Millions)': 'sum'}
               ).sort_values('Title', ascending=False).rename(
    columns={'Title': 'num_films',
             'Votes': 'votes_mean',
             'Revenue (Millions)': 'revenue_sum'}
)

                    revenue_sum  num_films     votes_mean
Director
Ridley Scott             719.06          8  260009.250000
Paul W.S. Anderson       208.92          6  109576.166667
David Yates             1630.51          6  338975.666667
M. Night Shyamalan       370.49          6  130712.333333
Michael Bay             1421.32          6  284421.833333
...                         ...        ...            ...
Jackson Stewart            0.00          1    2127.000000
J.D. Dillard               3.85          1     702.000000
Jeff Grace                 0.00          1     220.000000
Jee-woon Kim               0.54          1    2403.000000
Jalil Lespert              0.00          1     726.000000

[644 rows x 3 columns]

## Сохранение DataFrame в файл

In [27]:
df_gr = df.groupby('Director').agg(
    num_films=('Title', 'count'),
    votes_mean=('Votes', 'mean'),
    revenue_sum=('Revenue (Millions)', 'sum')
).sort_values('num_films', ascending=False)

df_gr.to_csv('/content/IMDB-Movie-Data-gr.csv')

In [28]:
df1 = pd.read_csv('/content/IMDB-Movie-Data-gr.csv', index_col='Director')
print(df1.shape)
df1.head()

(644, 3)

                    num_films     votes_mean  revenue_sum
Director
Ridley Scott                8  260009.250000       719.06
Paul W.S. Anderson          6  109576.166667       208.92
David Yates                 6  338975.666667      1630.51
M. Night Shyamalan          6  130712.333333       370.49
Michael Bay                 6  284421.833333      1421.32

## Задания

1. Загрузите файл `IMDB-Movie-Data.csv`. Выведите количество научно-фантастических фильмов. (1 балл)

In [29]:
# код

2. Выведите названия и режиссеров самого продолжительного и самого короткого фильмов. (2 балла)

In [30]:
# код

3. Выведите названия комедий, снятых в 2016 году. (1 балл)

In [31]:
# код

4. Составьте топ-10 наиболее прибыльных фильмов. Укажите название фильма, режиссера и полученную прибыль. (1 балл)

In [32]:
# код

5. Какая доля фильмов жанра `Sci-Fi` имеют значения `Metascore` выше 50? (1 балл)

In [33]:
# код

6. Получите названия фильмов, где снимался актер Leonardo DiCaprio. (1 балл)

In [34]:
# код

7. Сколько комедий выпускали каждый год? Отсортируйте результат в порядке убывания числа фильмов. Попробуйте решить двумя способами: с использованием функций groupby() и pivot_table(). (2 балла)

In [35]:
# код

8. Используя группировку из задания 7 и метод `get_group`, выведите названия комедий 2016 года (результат должен совпадать с заданием 3). (1 балл)

In [36]:
# код