# Библиотека Pandas

Pandas — самая популярная библиотека Python для обработки и анализа данных. Предлагает высокопроизводительные структуры данных и инструменты, которые решают следующие задачи:

* загрузка данных из внешних источников (электронный таблиц, баз данных, веб-страниц и прочих разных)
* сохранение данных в требуемом формате
* **объединение данных, полученных из разных источников**
* очистка данных от пропусков и ошибок
* группировка и агрегирование данных
* преобразование данных
* выполнение запросов для исследования данных
* создание новых атрибутов/признаков данных

In [ ]:
# импортируем библиотеку pandas. pd это общепринятое сокращение для неё
import pandas as pd

Объекты pandas:
- Series
- DataFrame

## Объект `Series`

In [ ]:
a = [10, 20, 30] # это список (list)
print(a)

[10, 20, 30]

In [ ]:
print(pd.Series(a)) # а это ряд (Series)

0    10
1    20
2    30
dtype: int64

В выводе два столбца: индексы и данные. `Series` (ряд) похож на массив с индексами, причем можно использовать различные метки индексов (а не только целые числа, начиная с 0). То есть он похож на словарь. Ряд в отличие от базовых типов данных — словарей и списков — содержит данные только одного типа, который можно задать.

In [ ]:
s = pd.Series(a, index=['a', 'b', 'c']) # создадим новый ряд, явно укажем метки для индексирования
print(s)

a    10
b    20
c    30
dtype: int64

In [ ]:
# извлекаем один и тот же элемент ряда
print(s[0])  # s.iloc[0] - правильнее
print(s['a'])

10
10

/tmp/ipython-input-1747658403.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])  # s.iloc[0] - правильнее

In [ ]:
print(s[['a', 'c']])

a    10
c    30
dtype: int64

In [ ]:
print(s[:'c']) # делаем срез

a    10
b    20
c    30
dtype: int64

In [ ]:
print(s[:2])

a    10
b    20
dtype: int64

Посмотрим на индексы объекта `s`.

In [ ]:
print(s.index)

Index(['a', 'b', 'c'], dtype='object')

Значения ряда можно получить с помощью свойства `values`.

In [ ]:
print(s.values)

[10 20 30]

Получим информацию об объекте.

In [ ]:
print(len(s))  # количество элементов (по нулевой оси)
print(s.shape) # количество строк и столбцов

3
(3,)

Над объектами Series можно совершать различные арифметические операции (`+`, `-`, `/`, `*`, ...). Они будут выполняться поэлементно в случае совпадения индексов.

In [ ]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([10, 20, 30, 40, 50])

s1 + s2

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [ ]:
# если ряды содержат разное количество элементов,
# то операция выполняется только для существующих элементов
s1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9])
s2 = pd.Series([10, 20, 30, 40, 50])

s1 + s2

0    11.0
1    22.0
2    33.0
3    44.0
4    55.0
5     NaN
6     NaN
7     NaN
8     NaN
dtype: float64

In [ ]:
# если ряды имеют разные метки индексов,
# то операция выполняется только для элементов с соответствующими индексами
s1 = pd.Series([1, 2, 3], index=['a', 'b', 'c'])
s2 = pd.Series([10, 20, 30, 40, 50])

s1 + s2

a   NaN
b   NaN
c   NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
dtype: float64

## Описательная статистика

Для объектов Series можно вычислить различные статистики, используя методы

* `count()` — количество непропущенных значений   
* `nunique()` — количество уникальных значений
* `unique()` — уникальные значения
* `value_counts()` — уникальные значения и их количества
* `mode()` — мода
* `mean()` — среднее арифметическое
* `median()` — медиана
* `sum()`  
* `min()` и `max()`

In [ ]:
s = pd.Series([10, 20, 30, 30, 30, 40, 50])

print('count =', s.count(), end='\n\n')
print('nunique =', s.nunique(), end='\n\n')
print('unique =', s.unique(), end='\n\n')
print('value_counts:\n', s.value_counts(), end='\n\n', sep='')
print('mode =', s.mode()[0], end='\n\n')
print('mean =', s.mean(), end='\n\n')
print('median =', s.median(), end='\n\n')

count = 7

nunique = 5

unique = [10 20 30 40 50]

value_counts:
30    3
10    1
20    1
40    1
50    1
Name: count, dtype: int64

mode = 30

mean = 30.0

median = 30.0

Создадим ряды из списка и словаря.

In [ ]:
ser1 = pd.Series(list('qwertyu'))
print(ser1, end='\n\n')
ser2 = pd.Series({'a':1., 'b':10., 'c':100.})
print(ser2, end='\n\n')

0    q
1    w
2    e
3    r
4    t
5    y
6    u
dtype: object

a      1.0
b     10.0
c    100.0
dtype: float64

Объединение объектов `Series`.

In [ ]:
# выравнивание данных по меткам индекса
print(ser1, end='\n\n')
print(ser2, end='\n\n')
print(ser1 + ser2) # проблема - индексы не совпадают

0    q
1    w
2    e
3    r
4    t
5    y
6    u
dtype: object

a      1.0
b     10.0
c    100.0
dtype: float64

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
5    NaN
6    NaN
a    NaN
b    NaN
c    NaN
dtype: object

In [ ]:
print(ser2.reset_index(drop=True)) # сбрасываем индексы

0      1.0
1     10.0
2    100.0
dtype: float64

In [ ]:
s1 + ser2

a      2.0
b     12.0
c    103.0
dtype: float64

In [ ]:
print(s1 + ser2.reset_index(drop=True)) # проблема решена?

a   NaN
b   NaN
c   NaN
0   NaN
1   NaN
2   NaN
dtype: float64

## Объект `DataFrame`

Объект `DataFrame` (датафрейм) представляет собой один или несколько объектов `Series`, упорядоченных по меткам идекса. Каждый ряд будет столбцом в датафрейме со своим именем.

Датафрейм подобен таблице реляционной базы данных, поскольку содержит столбцы разных типов, но данные в каждом столбце имеют один и тот же тип.

In [ ]:
df = pd.DataFrame({'letters':ser1, 'floats':ser2, 'integers':s})
print(df)

  letters  floats  integers
0       q     NaN      10.0
1       w     NaN      20.0
2       e     NaN      30.0
3       r     NaN      30.0
4       t     NaN      30.0
5       y     NaN      40.0
6       u     NaN      50.0
a     NaN     1.0       NaN
b     NaN    10.0       NaN
c     NaN   100.0       NaN

In [ ]:
ser2 = ser2.reset_index(drop=True)
df = pd.DataFrame({'letters':ser1, 'floats':ser2, 'integers':s})
print(df)

  letters  floats  integers
0       q     1.0        10
1       w    10.0        20
2       e   100.0        30
3       r     NaN        30
4       t     NaN        30
5       y     NaN        40
6       u     NaN        50

### Извлечение данных из датафрейма

Получим данные из определенного столбца (он же признак или атрибут).

In [ ]:
print(df['letters']) # это ряд

0    q
1    w
2    e
3    r
4    t
5    y
6    u
Name: letters, dtype: object

In [ ]:
print(df[['letters', 'integers']]) # несколько столбцов

  letters  integers
0       q        10
1       w        20
2       e        30
3       r        30
4       t        30
5       y        40
6       u        50

Извлекать строки из датафрейма можно с помощью методов `loc` и `iloc`.

Метод `loc` ищет по метке индекса, `iloc` — осуществляет поиск по позиции (начиная с 0).

In [ ]:
print(df.iloc[:, 0]) # получим все строки столбца letters

0    q
1    w
2    e
3    r
4    t
5    y
6    u
Name: letters, dtype: object

In [ ]:
print(df.loc[:, 'letters']) # то же

0    q
1    w
2    e
3    r
4    t
5    y
6    u
Name: letters, dtype: object

In [ ]:
print(df.iloc[:3, :2]) # получим первые три строки первых двух рядов

  letters  floats
0       q     1.0
1       w    10.0
2       e   100.0

In [ ]:
print(df.loc[:2, ['letters', 'floats']]) # то же

  letters  floats
0       q     1.0
1       w    10.0
2       e   100.0

In [ ]:
print(df[:3][['letters', 'floats']]) # то же

  letters  floats
0       q     1.0
1       w    10.0
2       e   100.0

Строки датафрейма можно отбирать по условию.

In [ ]:
print(df['integers'] < 30)

0     True
1     True
2    False
3    False
4    False
5    False
6    False
Name: integers, dtype: bool

In [ ]:
print(df[df['integers'] < 30])

  letters  floats  integers
0       q     1.0        10
1       w    10.0        20

### Операции над объектом `DataFrame`

Переименуем столбцы датафрейма.

In [ ]:
df.columns # получим наименования столбцов

Index(['letters', 'floats', 'integers'], dtype='object')

In [ ]:
df = df.rename(columns=
               {'letters':  'column1',
                'floats':   'column2',
                'integers': 'column3'
                })
df

  column1  column2  column3
0       q      1.0       10
1       w     10.0       20
2       e    100.0       30
3       r      NaN       30
4       t      NaN       30
5       y      NaN       40
6       u      NaN       50

Добавим новый столбец.

In [ ]:
df['column4'] = df['column3'] // 10
df

  column1  column2  column3  column4
0       q      1.0       10        1
1       w     10.0       20        2
2       e    100.0       30        3
3       r      NaN       30        3
4       t      NaN       30        3
5       y      NaN       40        4
6       u      NaN       50        5

In [ ]:
df['column5'] = pd.Series([0] * 7)
df

  column1  column2  column3  column4  column5
0       q      1.0       10        1        0
1       w     10.0       20        2        0
2       e    100.0       30        3        0
3       r      NaN       30        3        0
4       t      NaN       30        3        0
5       y      NaN       40        4        0
6       u      NaN       50        5        0

Удалить столбец можно с помощью:


*   `del` - удаляет на месте ряд из датафрейма
*   `pop()` - удаляет на месте и возвращает удаленный ряд
*   `drop(labels, axis=1)` - удаляет ряд и возвращает копию датафрейма без удаленного ряда. Исходный датафрейм не изменяется.

In [ ]:
del df['column5']
df

  column1  column2  column3  column4
0       q      1.0       10        1
1       w     10.0       20        2
2       e    100.0       30        3
3       r      NaN       30        3
4       t      NaN       30        3
5       y      NaN       40        4
6       u      NaN       50        5

In [ ]:
df.pop('column4')

0    1
1    2
2    3
3    3
4    3
5    4
6    5
Name: column4, dtype: int64

In [ ]:
df

  column1  column2  column3
0       q      1.0       10
1       w     10.0       20
2       e    100.0       30
3       r      NaN       30
4       t      NaN       30
5       y      NaN       40
6       u      NaN       50

Метод `drop()` можно использовать как для удаления столбцов, так и для удаления строк. Если нужно удалить столбцы, указываем `axis=1`. Если удаляем строки, то `axis=0`.

In [ ]:
df.drop('column3', axis=1)

  column1  column2
0       q      1.0
1       w     10.0
2       e    100.0
3       r      NaN
4       t      NaN
5       y      NaN
6       u      NaN

In [ ]:
df # исходный датафрейм не изменился

  column1  column2  column3
0       q      1.0       10
1       w     10.0       20
2       e    100.0       30
3       r      NaN       30
4       t      NaN       30
5       y      NaN       40
6       u      NaN       50

In [ ]:
df = df.drop('column3', axis=1)
# df.drop('column3', axis=1, inplace=True) # удаление на месте, если inplace=True
df

  column1  column2
0       q      1.0
1       w     10.0
2       e    100.0
3       r      NaN
4       t      NaN
5       y      NaN
6       u      NaN

In [ ]:
df.drop(6, axis=0, inplace=True) # удаляем последнюю строку
df

  column1  column2
0       q      1.0
1       w     10.0
2       e    100.0
3       r      NaN
4       t      NaN
5       y      NaN

In [ ]:
df

  column1  column2
0       q      1.0
1       w     10.0
2       e    100.0
3       r      NaN
4       t      NaN
5       y      NaN

Добавим новые строки.

In [ ]:
df.loc[10] = ['a', 100]
df

   column1  column2
0        q      1.0
1        w     10.0
2        e    100.0
3        r      NaN
4        t      NaN
5        y      NaN
10       a    100.0

 ## Конкатенация данных

Конкатенацию данных из разных объектов выполняют функцией `pd.concat()`. Конкатенация объектов `Series` приводит к образованию нового объекта `Series` с объединенными значениями.

In [ ]:
s1 = pd.Series([0, 1, 2])
s2 = pd.Series([3, 4, 5])

pd.concat([s1, s2])

0    0
1    1
2    2
0    3
1    4
2    5
dtype: int64

Получили новых объект `Series` с дублирующими метками индексов. В этом случае помогает сброс индекса:

In [ ]:
pd.concat([s1, s2]).reset_index(drop=True)

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

Можно также игнорировать метки индекса в исходных объектах:

In [ ]:
pd.concat([s1, s2], ignore_index=True) # тот же результат

0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64

### Конкатенация датафреймов

Объекты `DataFrame` конкатенируются аналогичным образом.

In [ ]:
df1 = pd.DataFrame({'a': s1, 'b': s2})
df1

   a  b
0  0  3
1  1  4
2  2  5

In [ ]:
df2 = pd.DataFrame({'a': s1 + 10, 'b': s2 + 10})
df2

    a   b
0  10  13
1  11  14
2  12  15

Выполним конкатенацию датафреймов:

In [ ]:
pd.concat([df1, df2])

    a   b
0   0   3
1   1   4
2   2   5
0  10  13
1  11  14
2  12  15

По умолчанию добавляются новые строки. Значения в соответствующих столбцах идут по порядку, указанному в функции `pd.concat()`. Здесь мы тоже получили дублирующие метки индекса строк.  

Рассмотрим вариант с несовпадающими названиями колонок объединяемых датафреймов.

In [ ]:
df3 = pd.DataFrame({'b': s1 * -1, 'c': s2 * -1})
pd.concat([df1, df3]) # совпадает только колонка b

     a  b    c
0  0.0  3  NaN
1  1.0  4  NaN
2  2.0  5  NaN
0  NaN  0 -3.0
1  NaN -1 -4.0
2  NaN -2 -5.0

В итоговом датафрейме отсутствующие значения столбцов заполнены `NaN` значениями.

Каждой группе данных в итоговом датафрейме можно дать свое название, используя параметр `keys`. Он создаст иерархический индекс строк:

In [ ]:
res = pd.concat([df1, df3], keys=['df1', 'df3'])
res

         a  b    c
df1 0  0.0  3  NaN
    1  1.0  4  NaN
    2  2.0  5  NaN
df3 0  NaN  0 -3.0
    1  NaN -1 -4.0
    2  NaN -2 -5.0

In [ ]:
res.loc['df1'] # извлекаем данные из итоговой таблицы, соответствующие первому датафрейму

     a  b   c
0  0.0  3 NaN
1  1.0  4 NaN
2  2.0  5 NaN

Функция `pd.concat()` позволяет задать ось, по которой произойдет добавление новых данных. По умолчанию добавляются строки (`axis=0`). Конкатенируем два объекта по оси столбцов, указав параметр `axis=1`:

In [ ]:
pd.concat([df1, df3], axis=1) # получим дублирующиеся наименования столбцов

   a  b  b  c
0  0  3  0 -3
1  1  4 -1 -4
2  2  5 -2 -5

Если метки индекса строк будут разными, то получим `NaN` значения:

In [ ]:
df4 = pd.DataFrame({'a': [0, 1, 2], 'b': [3, 4, 5]},
                   index=[2, 3, 4])
df4 # с df1 совпадает только метка 2

   a  b
2  0  3
3  1  4
4  2  5

In [ ]:
pd.concat([df1, df4], axis=1)

     a    b    a    b
0  0.0  3.0  NaN  NaN
1  1.0  4.0  NaN  NaN
2  2.0  5.0  0.0  3.0
3  NaN  NaN  1.0  4.0
4  NaN  NaN  2.0  5.0

Индексы строк у исходных датафреймов совпадают только меткой 2. Остальные метки не совпадают, поэтому в итоговом датафрейме стоят `NaN` значения.

### Тип соединения данных

По умолчанию конкатенация выполняет операцию **внешнего соединения** (outer join) индексных меток. Тип соединения можно изменить на **внутреннее соединение** (inner join), указав в качестве параметра `join='inner'`. В этом случае в итоговой таблице останутся только те строки, у которых совпадает метка:

In [ ]:
# выполним внутреннее соединение индексных меток по оси строк
pd.concat([df1, df4], axis=1, join='inner') # останется строка с меткой 2

   a  b  a  b
2  2  5  0  3

Выполним конкатенацию вдоль оси строк (`axis=0`), или другими словами - внешнее и внутреннее соединение индексных меток по оси столбцов.

In [ ]:
# выполним внешнее соединение индексных меток по оси столбцов
pd.concat([df1, df3], axis=0, join='outer') # получим все три столбца

     a  b    c
0  0.0  3  NaN
1  1.0  4  NaN
2  2.0  5  NaN
0  NaN  0 -3.0
1  NaN -1 -4.0
2  NaN -2 -5.0

In [ ]:
# выполним внутреннее соединение индексных меток по оси столбцов
pd.concat([df1, df3], axis=0, join='inner') # останется столбец с меткой b

   b
0  3
1  4
2  5
0  0
1 -1
2 -2

## Слияние данных

Функция `pd.merge()` и метод `.merge()` выполняют соединение датафреймов аналогично операции соединения для баз данных. В результате получим новый объект, который содержит объединенные данные двух объектов по совпадающим значениям в индексах строк или столбцов.

In [ ]:
# создадим датафрейм с авторами
authors = {
    'id_author': [1, 2, 3, 4, 5],
    'name': ['Ротфусс', 'Герберт', 'Хобб', 'Сандерсон', 'Пратчетт']
}
authors = pd.DataFrame(authors)
authors

   id_author       name
0          1    Ротфусс
1          2    Герберт
2          3       Хобб
3          4  Сандерсон
4          5   Пратчетт

In [ ]:
# создадим датафрейм с названиями книг и ID авторов
books = {
    'title': ['Имя ветра', 'Стража! Стража!', 'Шляпа, полная неба', 'Путь королей', 'Темная башня'],
    'id_author': [1, 5, 5, 4, 10]
}
books = pd.DataFrame(books)
books

                title  id_author
0           Имя ветра          1
1     Стража! Стража!          5
2  Шляпа, полная неба          5
3        Путь королей          4
4        Темная башня         10

Соединим датафреймы `books` и `authors` по общей колонке `id_author`. Метод `.merge()` применяет внутреннее соединение (`inner join`) по умолчанию.

In [ ]:
books.merge(authors)

                title  id_author       name
0           Имя ветра          1    Ротфусс
1     Стража! Стража!          5   Пратчетт
2  Шляпа, полная неба          5   Пратчетт
3        Путь королей          4  Сандерсон

Выше метод `.merge()` сам определил общую колонку по названию. Но мы всегда можем явно указать имя столбика, по которому нужно выполнить соединение в параметре `on`. Столбец, указанный в этом параметре, должен присутствовать в каждом датафрейме.

In [ ]:
books.merge(authors, on='id_author')

                title  id_author       name
0           Имя ветра          1    Ротфусс
1     Стража! Стража!          5   Пратчетт
2  Шляпа, полная неба          5   Пратчетт
3        Путь королей          4  Сандерсон

Мы также можем изменить тип соединения в параметре `how`. Допустимо использовать следующие значения параметра:

• `inner`: выполняет пересечение по соответствующим значениям общего столбика  
• `outer`: выполняет объединение строк из обоих датафреймов   
• `left`: присоединяет соответствующие строки к левому датафрейму из правого  
• `right`: присоединяет соответствующие строки к правому датафрейму из левого

In [ ]:
books.merge(authors, how='outer') # внешнее соединение books и authors

                title  id_author       name
0           Имя ветра          1    Ротфусс
1                 NaN          2    Герберт
2                 NaN          3       Хобб
3        Путь королей          4  Сандерсон
4     Стража! Стража!          5   Пратчетт
5  Шляпа, полная неба          5   Пратчетт
6        Темная башня         10        NaN

In [ ]:
authors.merge(books, how='outer') # внешнее соединение authors и books

   id_author       name               title
0          1    Ротфусс           Имя ветра
1          2    Герберт                 NaN
2          3       Хобб                 NaN
3          4  Сандерсон        Путь королей
4          5   Пратчетт     Стража! Стража!
5          5   Пратчетт  Шляпа, полная неба
6         10        NaN        Темная башня

In [ ]:
authors.merge(books, how='left') # левое соединение authors и books

   id_author       name               title
0          1    Ротфусс           Имя ветра
1          2    Герберт                 NaN
2          3       Хобб                 NaN
3          4  Сандерсон        Путь королей
4          5   Пратчетт     Стража! Стража!
5          5   Пратчетт  Шляпа, полная неба

In [ ]:
authors.merge(books, how='right') # правое соединение authors и books

   id_author       name               title
0          1    Ротфусс           Имя ветра
1          5   Пратчетт     Стража! Стража!
2          5   Пратчетт  Шляпа, полная неба
3          4  Сандерсон        Путь королей
4         10        NaN        Темная башня

## Задания

### Задание 1
Создайте ряд (Series) из 31 случайного числа (с помощью, например, `np.random.uniform(-15, -5, 31)`). Это будет средняя дневная температура за январь. Используйте для индексов ряда временную последовательность, сгенерированную, например, с помощью функции `pd.date_range('2026-01-01', periods=31, freq='D')`.  Выведите получившийся ряд. Посчитайте среднюю арифметическую температуру за весь период времени. (2 балла)

In [ ]:
import numpy as np
import pandas as pd

np.random.seed(42)
# код

### Задание 2

Создайте датафрейм, состоящий из ряда с дневной температурой из задания 1. Дайте новое имя нулевому столбцу - `temp_day`. Добавьте новый столбец `temp_night`, полученный из значений `temp_day`, умноженных на 1.5. (2 балла)

In [ ]:
# код

### Задание 3
Найдите разницу по модулю между ночной и дневной температурой на каждый день и добавьте ее в новый столбец `temp_diff`. Выведите разницу в температуре на 7 января. (2 балла)

In [ ]:
# код

### Задание 4

Выполните конкатенацию датафреймов `df_left` и `df_right` по оси строк, а затем по оси столбцов, используя функцию `concat()`. Замените дублирующие метки. (2 балла)

In [ ]:
left_data = {'col1': ['x', 'y', 'z'],
             'col2': [0, 1, 2]
             }
right_data = {'col1': ['a', 'b', 'c'],
              'col3': [6, 7, 8]
              }
df_left = pd.DataFrame(left_data, index=[0, 1, 2])
df_right = pd.DataFrame(right_data, index=[1, 2, 3])

In [ ]:
# код

### Задание 5

Выполните слияние датафреймов `orders` и `customers`, используя `.merge()`. Выведите заказы для каждого покупателя из таблицы `customers`, выбрав правильный тип соединения. (2 балла)

In [ ]:
# датафрейм с покупателями
customers = {'CustomerID': range(1, 4),
              'Name': ['Bob', 'Rob', 'Kob'],
              'Address': ['Address1', 'Address2', 'Address3']
             }
customers = pd.DataFrame(customers)
customers

   CustomerID Name   Address
0           1  Bob  Address1
1           2  Rob  Address2
2           3  Kob  Address3

In [ ]:
# датафрейм с заказами
orders = {'OrderID': range(1000, 1004),
          'CustomerID': [1, 2, 1, 5]
          }
orders = pd.DataFrame(orders)
orders

   OrderID  CustomerID
0     1000           1
1     1001           2
2     1002           1
3     1003           5

In [ ]:
# код